### ISSUE TITLE
Add the tqdm library

### ISSUE THREAD

**Issue by jamie-sgro** [fraymio/modis-tools#2]
**Is your feature request related to a problem? Please describe.**
When we begin download, I'd like to see how much fo the download is finished, and how quickly via a loading bar

**Describe the solution you'd like**
Import the super lightweight `tqdm` library and embed it into our loops that deal with downloading. Could be useful for queries that take a while as well to hear back from the api service

**Additional context**
Could be tough to infer the current state of a tqdm loading bar with multithreading. Have to make sure the loading bar doesn't increase and decrease as threads finish their tasks

**Comment by amanbagrecha** [comment]
Hi @jamie-sgro ,
I would like to contribute a PR on this issue. Can you assign it to me?
I have partially implemented what you suggested, with a multiple progress bar, each for a separate download.
Once the download is finished, it looks like the below picture.

![](https://i.imgur.com/e7x7prz.png)

If there is any specific requirement you think is useful, do let me know, ill add it to the PR.

Thanks,
Aman

**Comment by jamie-sgro** [comment]
That's great to hear @amanbagrecha, thanks for your contribution. Also I've drafted up my response to your new open issue. I'm just running it by the rest of the team to make sure my assumption regarding the `dio` holds true. I look forward to the PR for this tqdm issue!
