### ISSUE TITLE
GranuleFeed: Pydantic fails to parse protocol of href field

### ISSUE THREAD

**Issue by jparal** [fraymio/modis-tools#24]
**Description**
Hi, we are getting bunch of errors when calling `GranuleHandler.download_from_granules`. 
```
entry -> 287 -> links -> 9 -> href
URL scheme not permitted (type=value_error.url.scheme; allowed_schemes={'http', 'https'})
```

Digging a little deeper, it comes from the line bellow when parsing pydantic `GranuleFeed`:
https://github.com/fraymio/modis-tools/blob/main/modis_tools/resources.py#L119

It seems the href it fails on can also have an `s3` protocol:
```
feed["entry"][287]["links"][9]["href"]
's3://lp-prod-public/MOD11A1.061/MOD11A1.A2021001.h19v07.061.2021040151645/BROWSE.MOD11A1.A2021001.h19v07.061.2021040151652.2.jpg'
```

**Comment by amanbagrecha** [comment]
I think Pydantic still does not support s3 url validation. Only option I can think of is to make `href` (in modis_tools/models.py) of type `AnyUrl` (from `HttpUrl` currently) and reject `s3` paths when it tries to download the file

**Comment by alessiodl** [comment]
I'm experiencing this issue too...
