### ISSUE TITLE
New URL for LAADS DAAC hdf files

### ISSUE THREAD

**Issue by flogrows** [fraymio/modis-tools#53]
Hi there,

I'm getting the error "No matching link found" when trying to download MYD02HKM, MYD021KM or MYD03 data.

It looks like the host for hdf files in the granule info for all of these products has recently changed to
data.laadsdaac.earthdatacloud.nasa.gov

where previously it was
ladsweb.modaps.eosdis.nasa.gov

Thanks :)

**Comment by lmcindewar** [comment]
Hey, thanks for flagging this! Feel free to open a PR with a fix

**Comment by flogrows** [comment]
Ok thanks, I've never done that before but I'll give it a go!
