### ISSUE TITLE
Add .xml support for downloaded data

### ISSUE THREAD

**Issue by jtanwk** [fraymio/modis-tools#8]
**Is your feature request related to a problem? Please describe.**
Currently, MODIS data can only be downloaded in `hdf` format, but NASA's Earthdata portal makes MODIS data available in both `hdf` and `xml` formats.

**Describe the solution you'd like**
Add support to download the `xml` files from the Earthdata API

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cearlefraym** [comment]
This was added with https://github.com/fraymio/modis-tools/pull/31 where optional file types can be passed to `ext` arg.
